#!/bin/sh

mpd &
dunst &
dwmblocks &
fcitx &
unclutter &
xwallpaper --zoom ~/.config/wallpaper/futuristiccity.jpg &
xrandr --output HDMI-A-0 --mode 1920x1080 --rate 71.91 --dpi 103 &
redshift &
xset r rate 300 50 &
xrdb -merge $XDG_CONFIG_HOME/X11/xresources &
picom &

#lock
xset s 600 30 &
xss-lock -n "notify-send -u critical -t 10000 -- 'LOCKING screen in 30 seconds'" -- slock &

exec dwm
