#!/bin/sh

mpd &
dunst &
dwmblocks &
fcitx &
setxkbmap us -variant colemak -option caps:escape &
xset r rate 300 50 &
xrandr --output HDMI-A-0 --mode 1920x1080 --rate 71.91 --dpi 91.79 &
redshift &
xwallpaper --daemon --zoom $XDG_CONFIG_HOME/wallpaper/futuristiccity.jpg &
picom --experimental-backends --backend glx -b &
xrdb -merge $XDG_CONFIG_HOME/X11/xresources &

#lock
xset s 600 30 &
xss-lock -n "notify-send -u critical -t 10000 -- 'LOCKING screen in 30 seconds'" -- slock &

exec dwm
